plugins:
    - convertPathData:
        noSpaceAfterFlags: false
    - removeViewBox: true
    - removeDimensions: false
    - removeRasterImages: true
    - cleanupListOfValues: true
    - sortAttrs: true
